version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  migrate:
    build:
      context: .
      target: builder
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/todo?schema=public
    command: npx prisma db push
  app:
    build: .
    depends_on:
      - migrate
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/todo?schema=public
    ports:
      - "3000:3000"
    restart: unless-stopped
volumes:
  pgdata: